### PR TITLE
homed: add before pam_unix

### PR DESCRIPTION
**Pull request by xandris**
After this change, --homed has this effect:

```diff
--- stack/system-auth   2022-02-12 13:29:54.147933672 -0800
+++ stack.homed/system-auth     2022-02-12 13:29:34.087934022 -0800
@@ -1,10 +1,14 @@
 auth           required        pam_env.so
 auth           requisite       pam_faillock.so preauth
+auth            [success=2 default=ignore]      pam_systemd_home.so
 auth            [success=1 default=ignore]      pam_unix.so   try_first_pass
 auth           [default=die]   pam_faillock.so authfail
+account         [success=1 default=ignore]      pam_systemd_home.so
 account                required        pam_unix.so
 account         required        pam_faillock.so
+password        [success=1 default=ignore]      pam_systemd_home.so
 password        required        pam_unix.so try_first_pass  md5 shadow
 session                required        pam_limits.so
 session                required        pam_env.so
+session         [success=1 default=ignore]      pam_systemd_home.so
 session                required        pam_unix.so
diff -u stack/system-services stack.homed/system-services
--- stack/system-services       2022-02-12 13:29:54.163933671 -0800
+++ stack.homed/system-services 2022-02-12 13:29:34.099934022 -0800
@@ -3,4 +3,5 @@
 session         optional        pam_loginuid.so
 session                required        pam_limits.so
 session                required        pam_env.so
+session         [success=1 default=ignore]      pam_systemd_home.so
 session                required        pam_unix.so
```

### CODE REVIEW

**Comment by thesamesam** [comment]
Not tried it yet but this looks right. The only thing to keep an eye out for is whether in each type (auth/password/session) we had any success=N blocks which must be adjusted (if they came before the pam_systemd_home line), but you may as well have done that already - just pointing out the only real possible issue.

**Comment by xandris** [comment]
oh...there is a pam_krb5 with a success=3, but that might not always be right. even without this pr it can have a variable number of steps after it if --homed is toggled, which seems sus

**Comment by xandris** [comment]
i think the intent with krb5 was to jump over the faillock. with --krb5 only, that's 3 modules long, but with --krb5 --homed it's 4 modules, so i put in an inline conditional to capture that

pam can do substacks to avoid these shenanigans. at least i think that's the intent of the feature

**Comment by mikhailkoliada** [comment]
@xandris have you tested it on both pam_unix and homed systems? (i mean both account types co-exist)

**Comment by xandris** [comment]
> @xandris have you tested it on both pam_unix and homed systems? (i mean both account types co-exist)

@mikhailkoliada I have non-homed users on my system and I can still log in to them using pam_unix; is that what you mean? to clarify: i have users whose password hashes are in /etc/shadow and are authenticated by pam_unix, and i have users whose password hashes are in their JSON user record and are authenticated by pam_systemd_home, and both sets of users can log in properly

**Comment by mikhailkoliada** [comment]
> > @xandris have you tested it on both pam_unix and homed systems? (i mean both account types co-exist)
> 
> @mikhailkoliada I have non-homed users on my system and I can still log in to them using pam_unix; is that what you mean? to clarify: i have users whose password hashes are in /etc/shadow and are authenticated by pam_unix, and i have users whose password hashes are in their JSON user record and are authenticated by pam_systemd_home, and both sets of users can log in properly

yes that is what I was meaning, because, say, root account is still managed via flat shadow files, thanks :)

**Review by mikhailkoliada — APPROVED** [review]

**Pull request closed without merging**
